# API Key created in Ops Manager UI:
# Organization > Access Manager > Create API Key (role: Organization Owner)
# Remember to add the operator pod IP (or 10.42.0.0/16) to the API Access List.
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb-operator
stringData:
  user: "<PUBLIC_KEY>"
  publicApiKey: "<PRIVATE_KEY>"
