apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb-operator
spec:
  version: "8.0.22"
  adminCredentials: om-admin-secret
  externalConnectivity:
    type: LoadBalancer
  configuration:
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: remote
    mms.adminEmailAddr: support@example.com
    mms.fromEmailAddr: support@example.com
    mms.replyToEmailAddr: support@example.com
    mms.mail.hostname: example.com
    mms.mail.port: "466"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
  applicationDatabase:
    members: 3
    version: "8.2.0"

---
# Global Owner user for the initial Ops Manager setup only.
# For deploying MongoDB resources, an API Key is created in the OM UI
# (see 3-replica-set/secret.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: om-admin-secret
  namespace: mongodb-operator
type: Opaque
stringData:
  Username: "om-admin"
  Password: "Cemex-Demo-2026!" # strong password required or OM will not start monitoring AppDB
  FirstName: "Administrator"   # cannot be empty
  LastName: "Ops Manager"      # cannot be empty
